In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
dframe1 = DataFrame({"key": list("XZYZXX"), "data_set_1": np.arange(6)})
dframe1

data_set_1 key
0           0   X
1           1   Z
2           2   Y
3           3   Z
4           4   X
5           5   X

In [3]:
dframe2 = DataFrame({"key": list("QYZ"), "data_set_2": [1, 2, 3]})
dframe2

data_set_2 key
0           1   Q
1           2   Y
2           3   Z

In [4]:
pd.merge(dframe1, dframe2)
#Just keys Y,Z are common

data_set_1 key  data_set_2
0           1   Z           3
1           3   Z           3
2           2   Y           2

In [ ]:
pd.merge(dframe1, dframe2, on = 'key')

In [5]:
pd.merge(dframe1, dframe2, on = 'key', how = 'outer')

data_set_1 key  data_set_2
0         0.0   X         NaN
1         4.0   X         NaN
2         5.0   X         NaN
3         1.0   Z         3.0
4         3.0   Z         3.0
5         2.0   Y         2.0
6         NaN   Q         1.0

In [6]:
pd.merge(dframe1, dframe2, on = 'key', how = 'inner')

data_set_1 key  data_set_2
0           1   Z           3
1           3   Z           3
2           2   Y           2

In [ ]:
pd.merge(dframe1, dframe2, on = 'key', how = 'left')

In [ ]:
pd.merge(dframe1, dframe2, on = 'key', how = 'right')

In [7]:
df_left = DataFrame({"key1":['Qom', 'Qom', 'Rasht'], "key2":['one', 'two', 'one'], "left_data":[10, 20, 30]})

In [8]:
df_right = DataFrame({"key1":['Qom', 'Qom', 'Rasht', 'Rasht'], "key2":['one', 'one', 'one', 'two'], "left_data":[40, 50, 60, 70]})

In [ ]:
df_left

In [ ]:
df_right

In [ ]:
pd.merge(df_left, df_right, on = ['key1', 'key2'], how = 'outer')

In [ ]:
pd.merge(df_left, df_right, on = 'key1')

In [9]:
pd.merge(df_left, df_right, on = 'key1', suffixes= ['_lefty', '_righty'])

key1 key2_lefty  left_data_lefty key2_righty  left_data_righty
0    Qom        one               10         one                40
1    Qom        one               10         one                50
2    Qom        two               20         one                40
3    Qom        two               20         one                50
4  Rasht        one               30         one                60
5  Rasht        one               30         two                70

In [10]:
dframe_left = DataFrame({"key": list('XYZXY'), "data": range(5)})
dframe_right = DataFrame({"group_data": [10, 20]}, index = ['X', 'Y'])                         

In [12]:
dframe_left

data key
0     0   X
1     1   Y
2     2   Z
3     3   X
4     4   Y

In [13]:
dframe_right

group_data
X          10
Y          20

In [20]:
pd.merge(dframe_left, dframe_right)

MergeError: No common columns to perform merge on

In [ ]:
dframe_left_hr = DataFrame({"key1":list("ABCAB"), "key2":[10, 20, 30, 20, 30]
                           , "data_set" : np.arange(5)})
dframe_left_hr

In [ ]:
dframe_right_hr = DataFrame(np.arange(10).reshape(5, 2), index = [list('AAABB'), [20, 10, 10, 10, 20]]
                           , columns = ['col1', 'col2'])
dframe_right_hr

In [ ]:
pd.merge(dframe_left_hr, dframe_right_hr, left_on = ['key1', 'key2'], right_index = True)

In [ ]:
dframe_left

In [ ]:
dframe_right

In [19]:
dframe_left.join(dframe_right, on='key')

data key  group_data
0     0   X        10.0
1     1   Y        20.0
2     2   Z         NaN
3     3   X        10.0
4     4   Y        20.0

# Concatenate

In [21]:
arr1 = np.arange(9).reshape(3, 3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
np.concatenate([arr1, arr1, arr1], axis = 0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
np.concatenate([arr1, arr1], axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [ ]:
ser1 = Series([0, 1, 2], index = ["T", "U", "V"])
ser2 = Series([3, 4], index = ["X", "Y"])

In [ ]:
ser1

In [ ]:
ser2

In [ ]:
pd.concat([ser1, ser2])

In [ ]:
pd.concat([ser1, ser2], axis = 1)

In [ ]:
pd.concat([ser1, ser2], keys = ['cat1', 'cat2'])

In [ ]:
dframe1 = DataFrame(np.random.randn(4, 3), columns = ['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3, 3), columns = ['Y', 'Q', 'X'])

In [ ]:
dframe1

In [ ]:
dframe2

In [ ]:
pd.concat([dframe1, dframe2])

In [ ]:
pd.concat([dframe1, dframe2], ignore_index = True )